# Generated by Django 3.2.17 on 2023-02-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stream_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='paltform',
            new_name='platform',
        ),
    ]
