# Generated by Django 3.2.17 on 2023-02-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_paltform_movie_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='core.stream'),
        ),
    ]
