# Generated by Django 3.2.18 on 2023-02-15 02:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.movie_image_file_path),
        ),
    ]
